# Generated by Django 2.0.6 on 2021-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_auto_20210418_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
